package august.model;

import java.util.Date;

public class SssCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_customer.cu_id
     *
     * @mbg.generated
     */
    private String cuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_customer.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_customer.customer_psd
     *
     * @mbg.generated
     */
    private String customerPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_customer.customer_gen
     *
     * @mbg.generated
     */
    private String customerGen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_customer.brithday
     *
     * @mbg.generated
     */
    private Date brithday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_customer.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_customer.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_customer.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_customer.cu_id
     *
     * @return the value of sss_customer.cu_id
     *
     * @mbg.generated
     */
    public String getCuId() {
        return cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_customer.cu_id
     *
     * @param cuId the value for sss_customer.cu_id
     *
     * @mbg.generated
     */
    public void setCuId(String cuId) {
        this.cuId = cuId == null ? null : cuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_customer.customer_name
     *
     * @return the value of sss_customer.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_customer.customer_name
     *
     * @param customerName the value for sss_customer.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_customer.customer_psd
     *
     * @return the value of sss_customer.customer_psd
     *
     * @mbg.generated
     */
    public String getCustomerPsd() {
        return customerPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_customer.customer_psd
     *
     * @param customerPsd the value for sss_customer.customer_psd
     *
     * @mbg.generated
     */
    public void setCustomerPsd(String customerPsd) {
        this.customerPsd = customerPsd == null ? null : customerPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_customer.customer_gen
     *
     * @return the value of sss_customer.customer_gen
     *
     * @mbg.generated
     */
    public String getCustomerGen() {
        return customerGen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_customer.customer_gen
     *
     * @param customerGen the value for sss_customer.customer_gen
     *
     * @mbg.generated
     */
    public void setCustomerGen(String customerGen) {
        this.customerGen = customerGen == null ? null : customerGen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_customer.brithday
     *
     * @return the value of sss_customer.brithday
     *
     * @mbg.generated
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_customer.brithday
     *
     * @param brithday the value for sss_customer.brithday
     *
     * @mbg.generated
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_customer.tel
     *
     * @return the value of sss_customer.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_customer.tel
     *
     * @param tel the value for sss_customer.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_customer.address
     *
     * @return the value of sss_customer.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_customer.address
     *
     * @param address the value for sss_customer.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_customer.comment
     *
     * @return the value of sss_customer.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_customer.comment
     *
     * @param comment the value for sss_customer.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}