package august.model;

import java.util.Date;

public class SssCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_id
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.route_id
     *
     * @mbg.generated
     */
    private String routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_type
     *
     * @mbg.generated
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_origin
     *
     * @mbg.generated
     */
    private String carOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_pro_date
     *
     * @mbg.generated
     */
    private Date carProDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_buy_date
     *
     * @mbg.generated
     */
    private Date carBuyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_capacity
     *
     * @mbg.generated
     */
    private Integer carCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.car_state
     *
     * @mbg.generated
     */
    private Boolean carState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_car.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_id
     *
     * @return the value of sss_car.car_id
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_id
     *
     * @param carId the value for sss_car.car_id
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.route_id
     *
     * @return the value of sss_car.route_id
     *
     * @mbg.generated
     */
    public String getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.route_id
     *
     * @param routeId the value for sss_car.route_id
     *
     * @mbg.generated
     */
    public void setRouteId(String routeId) {
        this.routeId = routeId == null ? null : routeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_type
     *
     * @return the value of sss_car.car_type
     *
     * @mbg.generated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_type
     *
     * @param carType the value for sss_car.car_type
     *
     * @mbg.generated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_origin
     *
     * @return the value of sss_car.car_origin
     *
     * @mbg.generated
     */
    public String getCarOrigin() {
        return carOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_origin
     *
     * @param carOrigin the value for sss_car.car_origin
     *
     * @mbg.generated
     */
    public void setCarOrigin(String carOrigin) {
        this.carOrigin = carOrigin == null ? null : carOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_pro_date
     *
     * @return the value of sss_car.car_pro_date
     *
     * @mbg.generated
     */
    public Date getCarProDate() {
        return carProDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_pro_date
     *
     * @param carProDate the value for sss_car.car_pro_date
     *
     * @mbg.generated
     */
    public void setCarProDate(Date carProDate) {
        this.carProDate = carProDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_buy_date
     *
     * @return the value of sss_car.car_buy_date
     *
     * @mbg.generated
     */
    public Date getCarBuyDate() {
        return carBuyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_buy_date
     *
     * @param carBuyDate the value for sss_car.car_buy_date
     *
     * @mbg.generated
     */
    public void setCarBuyDate(Date carBuyDate) {
        this.carBuyDate = carBuyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_capacity
     *
     * @return the value of sss_car.car_capacity
     *
     * @mbg.generated
     */
    public Integer getCarCapacity() {
        return carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_capacity
     *
     * @param carCapacity the value for sss_car.car_capacity
     *
     * @mbg.generated
     */
    public void setCarCapacity(Integer carCapacity) {
        this.carCapacity = carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.car_state
     *
     * @return the value of sss_car.car_state
     *
     * @mbg.generated
     */
    public Boolean getCarState() {
        return carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.car_state
     *
     * @param carState the value for sss_car.car_state
     *
     * @mbg.generated
     */
    public void setCarState(Boolean carState) {
        this.carState = carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_car.comment
     *
     * @return the value of sss_car.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_car.comment
     *
     * @param comment the value for sss_car.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}