package august.model;

public class SssDeliveryplace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.de_p_id
     *
     * @mbg.generated
     */
    private String dePId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.mg_id
     *
     * @mbg.generated
     */
    private String mgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.de_p_name
     *
     * @mbg.generated
     */
    private String dePName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.provimce_name
     *
     * @mbg.generated
     */
    private String provimceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.mg_name
     *
     * @mbg.generated
     */
    private String mgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.de_p_tel
     *
     * @mbg.generated
     */
    private String dePTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.de_p_addr
     *
     * @mbg.generated
     */
    private String dePAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryplace.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.de_p_id
     *
     * @return the value of sss_deliveryplace.de_p_id
     *
     * @mbg.generated
     */
    public String getDePId() {
        return dePId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.de_p_id
     *
     * @param dePId the value for sss_deliveryplace.de_p_id
     *
     * @mbg.generated
     */
    public void setDePId(String dePId) {
        this.dePId = dePId == null ? null : dePId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.mg_id
     *
     * @return the value of sss_deliveryplace.mg_id
     *
     * @mbg.generated
     */
    public String getMgId() {
        return mgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.mg_id
     *
     * @param mgId the value for sss_deliveryplace.mg_id
     *
     * @mbg.generated
     */
    public void setMgId(String mgId) {
        this.mgId = mgId == null ? null : mgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.de_p_name
     *
     * @return the value of sss_deliveryplace.de_p_name
     *
     * @mbg.generated
     */
    public String getDePName() {
        return dePName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.de_p_name
     *
     * @param dePName the value for sss_deliveryplace.de_p_name
     *
     * @mbg.generated
     */
    public void setDePName(String dePName) {
        this.dePName = dePName == null ? null : dePName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.provimce_name
     *
     * @return the value of sss_deliveryplace.provimce_name
     *
     * @mbg.generated
     */
    public String getProvimceName() {
        return provimceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.provimce_name
     *
     * @param provimceName the value for sss_deliveryplace.provimce_name
     *
     * @mbg.generated
     */
    public void setProvimceName(String provimceName) {
        this.provimceName = provimceName == null ? null : provimceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.city_name
     *
     * @return the value of sss_deliveryplace.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.city_name
     *
     * @param cityName the value for sss_deliveryplace.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.mg_name
     *
     * @return the value of sss_deliveryplace.mg_name
     *
     * @mbg.generated
     */
    public String getMgName() {
        return mgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.mg_name
     *
     * @param mgName the value for sss_deliveryplace.mg_name
     *
     * @mbg.generated
     */
    public void setMgName(String mgName) {
        this.mgName = mgName == null ? null : mgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.de_p_tel
     *
     * @return the value of sss_deliveryplace.de_p_tel
     *
     * @mbg.generated
     */
    public String getDePTel() {
        return dePTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.de_p_tel
     *
     * @param dePTel the value for sss_deliveryplace.de_p_tel
     *
     * @mbg.generated
     */
    public void setDePTel(String dePTel) {
        this.dePTel = dePTel == null ? null : dePTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.de_p_addr
     *
     * @return the value of sss_deliveryplace.de_p_addr
     *
     * @mbg.generated
     */
    public String getDePAddr() {
        return dePAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.de_p_addr
     *
     * @param dePAddr the value for sss_deliveryplace.de_p_addr
     *
     * @mbg.generated
     */
    public void setDePAddr(String dePAddr) {
        this.dePAddr = dePAddr == null ? null : dePAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryplace.comment
     *
     * @return the value of sss_deliveryplace.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryplace.comment
     *
     * @param comment the value for sss_deliveryplace.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}