package august.model;

import java.math.BigDecimal;

public class SssDeliveryrange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.range_id
     *
     * @mbg.generated
     */
    private String rangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.de_p_id
     *
     * @mbg.generated
     */
    private String dePId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.area_id
     *
     * @mbg.generated
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.range_name
     *
     * @mbg.generated
     */
    private String rangeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.delivery_price
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_deliveryrange.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.range_id
     *
     * @return the value of sss_deliveryrange.range_id
     *
     * @mbg.generated
     */
    public String getRangeId() {
        return rangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.range_id
     *
     * @param rangeId the value for sss_deliveryrange.range_id
     *
     * @mbg.generated
     */
    public void setRangeId(String rangeId) {
        this.rangeId = rangeId == null ? null : rangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.de_p_id
     *
     * @return the value of sss_deliveryrange.de_p_id
     *
     * @mbg.generated
     */
    public String getDePId() {
        return dePId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.de_p_id
     *
     * @param dePId the value for sss_deliveryrange.de_p_id
     *
     * @mbg.generated
     */
    public void setDePId(String dePId) {
        this.dePId = dePId == null ? null : dePId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.area_id
     *
     * @return the value of sss_deliveryrange.area_id
     *
     * @mbg.generated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.area_id
     *
     * @param areaId the value for sss_deliveryrange.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.range_name
     *
     * @return the value of sss_deliveryrange.range_name
     *
     * @mbg.generated
     */
    public String getRangeName() {
        return rangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.range_name
     *
     * @param rangeName the value for sss_deliveryrange.range_name
     *
     * @mbg.generated
     */
    public void setRangeName(String rangeName) {
        this.rangeName = rangeName == null ? null : rangeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.delivery_price
     *
     * @return the value of sss_deliveryrange.delivery_price
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.delivery_price
     *
     * @param deliveryPrice the value for sss_deliveryrange.delivery_price
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_deliveryrange.comment
     *
     * @return the value of sss_deliveryrange.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_deliveryrange.comment
     *
     * @param comment the value for sss_deliveryrange.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}