package august.model;

public class SssManger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_manger.mg_id
     *
     * @mbg.generated
     */
    private String mgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_manger.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_manger.manger_name
     *
     * @mbg.generated
     */
    private String mangerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_manger.manger_psd
     *
     * @mbg.generated
     */
    private String mangerPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_manger.manger_gen
     *
     * @mbg.generated
     */
    private String mangerGen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_manger.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_manger.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_manger.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_manger.mg_id
     *
     * @return the value of sss_manger.mg_id
     *
     * @mbg.generated
     */
    public String getMgId() {
        return mgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_manger.mg_id
     *
     * @param mgId the value for sss_manger.mg_id
     *
     * @mbg.generated
     */
    public void setMgId(String mgId) {
        this.mgId = mgId == null ? null : mgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_manger.role_id
     *
     * @return the value of sss_manger.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_manger.role_id
     *
     * @param roleId the value for sss_manger.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_manger.manger_name
     *
     * @return the value of sss_manger.manger_name
     *
     * @mbg.generated
     */
    public String getMangerName() {
        return mangerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_manger.manger_name
     *
     * @param mangerName the value for sss_manger.manger_name
     *
     * @mbg.generated
     */
    public void setMangerName(String mangerName) {
        this.mangerName = mangerName == null ? null : mangerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_manger.manger_psd
     *
     * @return the value of sss_manger.manger_psd
     *
     * @mbg.generated
     */
    public String getMangerPsd() {
        return mangerPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_manger.manger_psd
     *
     * @param mangerPsd the value for sss_manger.manger_psd
     *
     * @mbg.generated
     */
    public void setMangerPsd(String mangerPsd) {
        this.mangerPsd = mangerPsd == null ? null : mangerPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_manger.manger_gen
     *
     * @return the value of sss_manger.manger_gen
     *
     * @mbg.generated
     */
    public String getMangerGen() {
        return mangerGen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_manger.manger_gen
     *
     * @param mangerGen the value for sss_manger.manger_gen
     *
     * @mbg.generated
     */
    public void setMangerGen(String mangerGen) {
        this.mangerGen = mangerGen == null ? null : mangerGen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_manger.tel
     *
     * @return the value of sss_manger.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_manger.tel
     *
     * @param tel the value for sss_manger.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_manger.address
     *
     * @return the value of sss_manger.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_manger.address
     *
     * @param address the value for sss_manger.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_manger.comment
     *
     * @return the value of sss_manger.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_manger.comment
     *
     * @param comment the value for sss_manger.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}