package august.model;

import java.math.BigDecimal;

public class SssOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.car_id
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.cu_id
     *
     * @mbg.generated
     */
    private String cuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.post_name
     *
     * @mbg.generated
     */
    private String postName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.post_p_Tel
     *
     * @mbg.generated
     */
    private String postPTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.post_p_addr
     *
     * @mbg.generated
     */
    private String postPAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.get_p_name
     *
     * @mbg.generated
     */
    private String getPName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.get_p_tel
     *
     * @mbg.generated
     */
    private String getPTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.get_p_addr
     *
     * @mbg.generated
     */
    private String getPAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.good_weight
     *
     * @mbg.generated
     */
    private Integer goodWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.order_state
     *
     * @mbg.generated
     */
    private String orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.transport_price
     *
     * @mbg.generated
     */
    private BigDecimal transportPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.delivery_price
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.total_price
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sss_order.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.order_id
     *
     * @return the value of sss_order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.order_id
     *
     * @param orderId the value for sss_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.car_id
     *
     * @return the value of sss_order.car_id
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.car_id
     *
     * @param carId the value for sss_order.car_id
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.cu_id
     *
     * @return the value of sss_order.cu_id
     *
     * @mbg.generated
     */
    public String getCuId() {
        return cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.cu_id
     *
     * @param cuId the value for sss_order.cu_id
     *
     * @mbg.generated
     */
    public void setCuId(String cuId) {
        this.cuId = cuId == null ? null : cuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.post_name
     *
     * @return the value of sss_order.post_name
     *
     * @mbg.generated
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.post_name
     *
     * @param postName the value for sss_order.post_name
     *
     * @mbg.generated
     */
    public void setPostName(String postName) {
        this.postName = postName == null ? null : postName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.post_p_Tel
     *
     * @return the value of sss_order.post_p_Tel
     *
     * @mbg.generated
     */
    public String getPostPTel() {
        return postPTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.post_p_Tel
     *
     * @param postPTel the value for sss_order.post_p_Tel
     *
     * @mbg.generated
     */
    public void setPostPTel(String postPTel) {
        this.postPTel = postPTel == null ? null : postPTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.post_p_addr
     *
     * @return the value of sss_order.post_p_addr
     *
     * @mbg.generated
     */
    public String getPostPAddr() {
        return postPAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.post_p_addr
     *
     * @param postPAddr the value for sss_order.post_p_addr
     *
     * @mbg.generated
     */
    public void setPostPAddr(String postPAddr) {
        this.postPAddr = postPAddr == null ? null : postPAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.get_p_name
     *
     * @return the value of sss_order.get_p_name
     *
     * @mbg.generated
     */
    public String getGetPName() {
        return getPName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.get_p_name
     *
     * @param getPName the value for sss_order.get_p_name
     *
     * @mbg.generated
     */
    public void setGetPName(String getPName) {
        this.getPName = getPName == null ? null : getPName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.get_p_tel
     *
     * @return the value of sss_order.get_p_tel
     *
     * @mbg.generated
     */
    public String getGetPTel() {
        return getPTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.get_p_tel
     *
     * @param getPTel the value for sss_order.get_p_tel
     *
     * @mbg.generated
     */
    public void setGetPTel(String getPTel) {
        this.getPTel = getPTel == null ? null : getPTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.get_p_addr
     *
     * @return the value of sss_order.get_p_addr
     *
     * @mbg.generated
     */
    public String getGetPAddr() {
        return getPAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.get_p_addr
     *
     * @param getPAddr the value for sss_order.get_p_addr
     *
     * @mbg.generated
     */
    public void setGetPAddr(String getPAddr) {
        this.getPAddr = getPAddr == null ? null : getPAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.goods_name
     *
     * @return the value of sss_order.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.goods_name
     *
     * @param goodsName the value for sss_order.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.good_weight
     *
     * @return the value of sss_order.good_weight
     *
     * @mbg.generated
     */
    public Integer getGoodWeight() {
        return goodWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.good_weight
     *
     * @param goodWeight the value for sss_order.good_weight
     *
     * @mbg.generated
     */
    public void setGoodWeight(Integer goodWeight) {
        this.goodWeight = goodWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.order_type
     *
     * @return the value of sss_order.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.order_type
     *
     * @param orderType the value for sss_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.order_state
     *
     * @return the value of sss_order.order_state
     *
     * @mbg.generated
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.order_state
     *
     * @param orderState the value for sss_order.order_state
     *
     * @mbg.generated
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState == null ? null : orderState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.transport_price
     *
     * @return the value of sss_order.transport_price
     *
     * @mbg.generated
     */
    public BigDecimal getTransportPrice() {
        return transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.transport_price
     *
     * @param transportPrice the value for sss_order.transport_price
     *
     * @mbg.generated
     */
    public void setTransportPrice(BigDecimal transportPrice) {
        this.transportPrice = transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.delivery_price
     *
     * @return the value of sss_order.delivery_price
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.delivery_price
     *
     * @param deliveryPrice the value for sss_order.delivery_price
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.total_price
     *
     * @return the value of sss_order.total_price
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.total_price
     *
     * @param totalPrice the value for sss_order.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sss_order.comment
     *
     * @return the value of sss_order.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sss_order.comment
     *
     * @param comment the value for sss_order.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}