package august.dao;

import august.model.SssCar;
import java.util.List;

public interface SssCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_car
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_car
     *
     * @mbg.generated
     */
    int insert(SssCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_car
     *
     * @mbg.generated
     */
    SssCar selectByPrimaryKey(String carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_car
     *
     * @mbg.generated
     */
    List<SssCar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_car
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssCar record);
}