package august.dao;

import august.model.SssCity;
import java.util.List;

public interface SssCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_city
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_city
     *
     * @mbg.generated
     */
    int insert(SssCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_city
     *
     * @mbg.generated
     */
    SssCity selectByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_city
     *
     * @mbg.generated
     */
    List<SssCity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssCity record);
}