package august.dao;

import august.model.SssDeliveryplace;
import java.util.List;

public interface SssDeliveryplaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryplace
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String dePId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryplace
     *
     * @mbg.generated
     */
    int insert(SssDeliveryplace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryplace
     *
     * @mbg.generated
     */
    SssDeliveryplace selectByPrimaryKey(String dePId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryplace
     *
     * @mbg.generated
     */
    List<SssDeliveryplace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryplace
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssDeliveryplace record);
}