package august.dao;

import august.model.SssDeliveryrange;
import java.util.List;

public interface SssDeliveryrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryrange
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryrange
     *
     * @mbg.generated
     */
    int insert(SssDeliveryrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryrange
     *
     * @mbg.generated
     */
    SssDeliveryrange selectByPrimaryKey(String rangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryrange
     *
     * @mbg.generated
     */
    List<SssDeliveryrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryrange
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssDeliveryrange record);
}