package august.dao;

import august.model.SssDeliveryreceipt;
import java.util.List;

public interface SssDeliveryreceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deliveryReceiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    int insert(SssDeliveryreceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    SssDeliveryreceipt selectByPrimaryKey(String deliveryReceiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    List<SssDeliveryreceipt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_deliveryreceipt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssDeliveryreceipt record);
}