package august.dao;

import august.model.SssManger;
import java.util.List;

public interface SssMangerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_manger
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String mgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_manger
     *
     * @mbg.generated
     */
    int insert(SssManger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_manger
     *
     * @mbg.generated
     */
    SssManger selectByPrimaryKey(String mgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_manger
     *
     * @mbg.generated
     */
    List<SssManger> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_manger
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssManger record);
}