package august.dao;

import august.model.SssPrivance;
import java.util.List;

public interface SssPrivanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_privance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_privance
     *
     * @mbg.generated
     */
    int insert(SssPrivance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_privance
     *
     * @mbg.generated
     */
    SssPrivance selectByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_privance
     *
     * @mbg.generated
     */
    List<SssPrivance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_privance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssPrivance record);
}