package august.dao;

import august.model.SssRoute;
import java.util.List;

public interface SssRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_route
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_route
     *
     * @mbg.generated
     */
    int insert(SssRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_route
     *
     * @mbg.generated
     */
    SssRoute selectByPrimaryKey(String routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_route
     *
     * @mbg.generated
     */
    List<SssRoute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sss_route
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SssRoute record);
}